disabled_rules: # Regras que não queremos usar
  - trailing_whitespace
  - line_length
opt_in_rules: # Regras extras que queremos usar
  - empty_count
  - force_unwrapping
  - explicit_init
  - closure_spacing
  - private_outlet
excluded: # Pastas que o SwiftLint deve ignorar
  - Pods
  - Carthage
